name: AppScan CodeSweep Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required for AppScan to report findings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Java
        uses: actions/setup-java@v4 # Updated to v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Run AppScan CodeSweep
        uses: https://github.com/HCL-TECH-SOFTWARE/appscan-codesweep-action@v1.0.4
        with:
          api_key: ${{ secrets.APPSCAN_API_KEY }}
