name: Bandit Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -r . --severity-level high --confidence-level high --format sarif -o bandit-results.sarif
        continue-on-error: false # Fail job if issues found

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif
