name: Bandit Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit_scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required to report security findings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -r . --severity-level high --confidence-level high || echo "Bandit scan completed with findings."
